#!/usr/bin/env python3
"""
Rebuild SDK documentation pages from Speakeasy-generated content.
Fetches real SDK docs from raijinlabs/lucid-ai-sdk repo and creates
proper Mintlify MDX pages.
"""

import urllib.request
import json
import os

DOCS_ROOT = os.environ.get("DOCS_ROOT", os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SDK_BASE = "https://raw.githubusercontent.com/raijinlabs/lucid-ai-sdk/main/typescript"
API_BASE = "https://api.github.com/repos/raijinlabs/lucid-ai-sdk/contents/typescript"
HEADERS = {"User-Agent": "Mozilla/5.0"}


def fetch(url):
    req = urllib.request.Request(url, headers=HEADERS)
    return urllib.request.urlopen(req).read().decode()


def fetch_json(url):
    return json.loads(fetch(url))


def fetch_sdk_namespace_docs(namespace):
    """Fetch all method docs from a Speakeasy SDK namespace."""
    try:
        files = fetch_json(f"{API_BASE}/docs/sdks/{namespace}")
        docs = []
        for f in files:
            if f["name"].endswith(".md"):
                content = fetch(f"https://raw.githubusercontent.com/raijinlabs/lucid-ai-sdk/main/typescript/docs/sdks/{namespace}/{f['name']}")
                docs.append({"name": f["name"].replace(".md", ""), "content": content})
        return docs
    except Exception as e:
        print(f"  Warning: Could not fetch {namespace}: {e}")
        return []


def extract_method_table(docs):
    """Extract method signatures from Speakeasy docs into a table."""
    rows = []
    for doc in docs:
        # Extract the first heading and description
        lines = doc["content"].split("\n")
        method_name = doc["name"]
        description = ""
        for line in lines:
            if line.startswith("##") and not line.startswith("###"):
                continue
            if line.strip() and not line.startswith("#") and not line.startswith(">") and not line.startswith("```"):
                description = line.strip()
                break
        rows.append((method_name, description))
    return rows


def extract_code_examples(content, max_examples=2):
    """Extract TypeScript code examples from markdown content."""
    examples = []
    in_code = False
    current = []
    for line in content.split("\n"):
        if line.strip().startswith("```typescript") or line.strip().startswith("```ts"):
            in_code = True
            current = []
        elif line.strip() == "```" and in_code:
            in_code = False
            if current:
                examples.append("\n".join(current))
            if len(examples) >= max_examples:
                break
        elif in_code:
            current.append(line)
    return examples


def write_file(path, content):
    full_path = os.path.join(DOCS_ROOT, path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Updated: {full_path}")


# ============================================================
# Fetch all Speakeasy content
# ============================================================
print("Fetching Speakeasy SDK documentation...")

readme = fetch(f"{SDK_BASE}/README.md")
usage = fetch(f"{SDK_BASE}/USAGE.md")
functions = fetch(f"{SDK_BASE}/FUNCTIONS.md")

print("Fetching namespace docs...")
namespaces = {}
for ns in ["passports", "match", "run", "receipts", "epochs", "payouts", "agents", "compute", "health"]:
    print(f"  Fetching {ns}...")
    namespaces[ns] = fetch_sdk_namespace_docs(ns)

# ============================================================
# 1. Main TypeScript SDK page
# ============================================================
print("\nBuilding SDK pages...")

# Extract real examples from README
readme_examples = extract_code_examples(readme, max_examples=3)
quick_start = readme_examples[0] if readme_examples else ""
passport_example = readme_examples[1] if len(readme_examples) > 1 else ""

write_file("sdks/typescript.mdx", f'''---
title: "TypeScript SDK"
description: "Developer-friendly & type-safe TypeScript SDK for the LucidLayer API"
---

import {{ Callout }} from "mintlify/components";

# TypeScript SDK

[![npm](https://img.shields.io/npm/v/raijin-labs-lucid-ai)](https://www.npmjs.com/package/raijin-labs-lucid-ai)
[![License: MIT](https://img.shields.io/badge/license-MIT-blue)](https://github.com/raijinlabs/lucid-ai-sdk/blob/main/LICENSE)

Developer-friendly & type-safe TypeScript SDK for the [LucidLayer API](https://www.lucid.foundation/), generated by [Speakeasy](https://speakeasy.com/).

## Installation

```bash
npm install raijin-labs-lucid-ai
```

<Callout type="info">
  This package is published with CommonJS and ES Modules (ESM) support.
</Callout>

## Quick Start

```typescript
{quick_start}
```

## SDK Namespaces

The SDK is organized into namespaces matching the API groups:

| Namespace | Description | Methods |
|-----------|-------------|---------|
| `sdk.passports` | Identity passports (model, compute, tool, dataset, agent) | {len(namespaces.get("passports", []))} |
| `sdk.match` | Model matching and routing | {len(namespaces.get("match", []))} |
| `sdk.run` | Inference execution | {len(namespaces.get("run", []))} |
| `sdk.receipts` | Cryptographic receipts and verification | {len(namespaces.get("receipts", []))} |
| `sdk.epochs` | Epoch management and anchoring | {len(namespaces.get("epochs", []))} |
| `sdk.payouts` | Payout calculations | {len(namespaces.get("payouts", []))} |
| `sdk.agents` | AI Agent orchestration | {len(namespaces.get("agents", []))} |
| `sdk.compute` | Compute node management | {len(namespaces.get("compute", []))} |
| `sdk.health` | System health checks | {len(namespaces.get("health", []))} |

## Authentication

```typescript
import {{ RaijinLabsLucidAi }} from "raijin-labs-lucid-ai";

const sdk = new RaijinLabsLucidAi({{
  serverURL: "https://api.lucid.foundation",
  // API key authentication (when required)
  // security: {{ bearerAuth: "YOUR_API_KEY" }}
}});
```

## Passport CRUD Example

```typescript
{passport_example}
```

## Standalone Functions (Tree-Shaking)

For browser and serverless environments, every method is available as a standalone function for optimal tree-shaking:

```typescript
import {{ RaijinLabsLucidAiCore }} from "raijin-labs-lucid-ai/core.js";
import {{ passportsCreate }} from "raijin-labs-lucid-ai/funcs/passportsCreate.js";

const client = new RaijinLabsLucidAiCore();

const res = await passportsCreate(client, {{
  type: "model",
  owner: "YOUR_WALLET",
  metadata: {{ schema_version: "1.0", name: "my-model" }},
}});

if (res.ok) {{
  console.log(res.value);
}}
```

<Callout type="tip">
  Standalone functions return `Result<Value, Error>` instead of throwing, making them ideal for React and similar frameworks.
</Callout>

## Error Handling

```typescript
import {{ SDKValidationError }} from "raijin-labs-lucid-ai/models/errors";

try {{
  const result = await sdk.passports.create({{ /* ... */ }});
}} catch (err) {{
  if (err instanceof SDKValidationError) {{
    console.error("Validation error:", err.message);
  }}
  throw err;
}}
```

## Supported Runtimes

- Node.js >= 18
- Deno
- Bun
- Cloudflare Workers
- Edge runtimes (Vercel Edge, etc.)

## Links

- [SDK GitHub Repository](https://github.com/raijinlabs/lucid-ai-sdk/tree/main/typescript)
- [npm Package](https://www.npmjs.com/package/raijin-labs-lucid-ai)
- [Full SDK Reference (Speakeasy-generated)](https://github.com/raijinlabs/lucid-ai-sdk/tree/main/typescript/docs/sdks)
- [Model Types Reference](https://github.com/raijinlabs/lucid-ai-sdk/tree/main/typescript/docs/models)
- [Standalone Functions](https://github.com/raijinlabs/lucid-ai-sdk/blob/main/typescript/FUNCTIONS.md)
''')


# ============================================================
# 2. Per-namespace SDK pages (Passports, Inference, Receipts, Agents)
# ============================================================

def build_namespace_page(title, description, ns_names, sdk_prefix):
    """Build an MDX page from one or more Speakeasy namespace docs."""
    all_docs = []
    for ns_name in ns_names:
        all_docs.extend(namespaces.get(ns_name, []))
    
    methods_section = ""
    for doc in all_docs:
        # Extract method title
        lines = doc["content"].split("\n")
        method_title = doc["name"]
        for line in lines:
            if line.startswith("# "):
                method_title = line.replace("# ", "").strip()
                break
        
        # Extract description (first paragraph after title)
        desc_lines = []
        found_title = False
        for line in lines:
            if line.startswith("# "):
                found_title = True
                continue
            if found_title:
                if line.strip() == "":
                    if desc_lines:
                        break
                    continue
                if line.startswith("#") or line.startswith("```"):
                    break
                desc_lines.append(line.strip())
        description_text = " ".join(desc_lines) if desc_lines else ""
        
        # Extract first code example
        examples = extract_code_examples(doc["content"], max_examples=1)
        code_block = f"\n```typescript\n{examples[0]}\n```\n" if examples else ""
        
        methods_section += f"\n### `{method_title}`\n\n{description_text}\n{code_block}\n---\n"
    
    return f'''---
title: "{title}"
description: "{description}"
---

# {title}

{description}

**Full Speakeasy-generated reference**: [View on GitHub](https://github.com/raijinlabs/lucid-ai-sdk/tree/main/typescript/docs/sdks/{ns_names[0]})

## Methods
{methods_section}
'''


# Passports SDK
write_file("sdks/typescript-passports.mdx", build_namespace_page(
    "Passports SDK",
    "Create, list, update, and delete identity passports for models, compute nodes, tools, datasets, and agents.",
    ["passports"],
    "sdk.passports"
))

# Inference SDK (match + run)
write_file("sdks/typescript-inference.mdx", build_namespace_page(
    "Inference SDK",
    "Run AI inference, match models to requests, and execute chat completions.",
    ["match", "run"],
    "sdk.match / sdk.run"
))

# Receipts SDK
write_file("sdks/typescript-receipts.mdx", build_namespace_page(
    "Receipts SDK",
    "Create, verify, and manage cryptographic receipts with Merkle proofs.",
    ["receipts"],
    "sdk.receipts"
))

# Agents SDK
write_file("sdks/typescript-agents.mdx", build_namespace_page(
    "Agents SDK",
    "Initialize agents, submit epochs, generate proofs, and orchestrate AI agent workflows.",
    ["agents"],
    "sdk.agents"
))

# ============================================================
# 3. Python SDK (placeholder with real package info)
# ============================================================
write_file("sdks/python.mdx", '''---
title: "Python SDK"
description: "Python SDK for the LucidLayer API (coming soon)"
---

# Python SDK

<Callout type="warning">
  The Python SDK is under development. Use the [REST API](/sdks/rest) or [TypeScript SDK](/sdks/typescript) in the meantime.
</Callout>

## Coming Soon

A Speakeasy-generated Python SDK will be available at:

- **Package**: `raijin-labs-lucid-ai` (PyPI)
- **Repository**: [github.com/raijinlabs/lucid-ai-sdk](https://github.com/raijinlabs/lucid-ai-sdk)

## Current Options

In the meantime, you can use:

1. **REST API** — Direct HTTP calls with any Python HTTP library
2. **TypeScript SDK** — Full-featured SDK available now

```python
# Preview of what the Python SDK will look like
import httpx

BASE_URL = "https://api.lucid.foundation"

# List passports
response = httpx.get(f"{BASE_URL}/v1/passports")
passports = response.json()

# Run chat completion
response = httpx.post(f"{BASE_URL}/v1/chat/completions", json={
    "model": "your-model-passport-id",
    "messages": [{"role": "user", "content": "Hello!"}],
})
result = response.json()
```
''')

# ============================================================
# 4. REST API page
# ============================================================
write_file("sdks/rest.mdx", '''---
title: "REST API"
description: "Direct HTTP access to all LucidLayer API endpoints"
---

# REST API

All LucidLayer API endpoints are available via standard HTTP requests. The API follows REST conventions with JSON request/response bodies.

## Base URL

```
https://api.lucid.foundation
```

## Authentication

Include your API key as a Bearer token:

```bash
curl -H "Authorization: Bearer YOUR_API_KEY" \\
  https://api.lucid.foundation/v1/passports
```

For passport ownership operations, include the owner address header:

```bash
curl -H "X-Owner-Address: YOUR_WALLET_ADDRESS" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  https://api.lucid.foundation/v1/passports
```

## Quick Examples

### List Passports

```bash
curl https://api.lucid.foundation/v1/passports?per_page=10
```

### Create a Passport

```bash
curl -X POST https://api.lucid.foundation/v1/passports \\
  -H "Content-Type: application/json" \\
  -d '{
    "type": "model",
    "owner": "YOUR_WALLET",
    "name": "my-model",
    "version": "1.0.0",
    "metadata": {
      "schema_version": "1.0",
      "name": "my-model"
    }
  }'
```

### Run Chat Completion

```bash
curl -X POST https://api.lucid.foundation/v1/chat/completions \\
  -H "Content-Type: application/json" \\
  -d '{
    "model": "MODEL_PASSPORT_ID",
    "messages": [
      {"role": "user", "content": "Explain LucidLayer in one sentence."}
    ]
  }'
```

### Check System Health

```bash
curl https://api.lucid.foundation/health
```

## API Groups

| Group | Base Path | Endpoints |
|-------|-----------|-----------|
| Passports | `/v1/passports` | 8 |
| Inference | `/v1/chat/completions`, `/v1/run`, `/v1/match` | 5 |
| Convenience | `/v1/models`, `/v1/compute`, `/v1/tools`, `/v1/datasets`, `/v1/agents` | 5 |
| Receipts | `/v1/receipts`, `/v1/verify`, `/v1/mmr` | 9 |
| Epochs | `/v1/epochs` | 8 |
| Payouts | `/v1/payouts` | 4 |
| Compute | `/v1/compute/nodes` | 2 |
| Health | `/health` | 7 |
| Agents | `/api/agents` | 14+ |

## Full API Reference

See the [API Reference](/api-reference/introduction) tab for interactive documentation of all 65+ endpoints, auto-generated from the [OpenAPI spec](https://raw.githubusercontent.com/raijinlabs/lucid-ai-sdk/main/openapi-with-code-samples.yaml).
''')

# ============================================================
# 5. MCP Server page
# ============================================================
write_file("sdks/mcp-server.mdx", '''---
title: "MCP Server"
description: "Model Context Protocol server for LucidLayer API integration with AI tools"
---

# LucidLayer MCP Server

The LucidLayer MCP (Model Context Protocol) server enables AI coding tools like Cursor, Claude Code, and Windsurf to interact directly with the LucidLayer API.

## Installation

The MCP server is included in the SDK repository:

```bash
git clone https://github.com/raijinlabs/lucid-ai-sdk.git
cd lucid-ai-sdk/mcp
npm install
```

## Configuration

### Cursor

Add to your `.cursor/mcp.json`:

```json
{
  "mcpServers": {
    "lucidlayer": {
      "command": "npx",
      "args": ["-y", "@raijinlabs/mcp-server"],
      "env": {
        "LUCID_API_KEY": "your-api-key",
        "LUCID_API_URL": "https://api.lucid.foundation"
      }
    }
  }
}
```

### Claude Code

Add to your Claude Code MCP settings:

```json
{
  "mcpServers": {
    "lucidlayer": {
      "command": "npx",
      "args": ["-y", "@raijinlabs/mcp-server"],
      "env": {
        "LUCID_API_KEY": "your-api-key"
      }
    }
  }
}
```

## Available Tools

The MCP server exposes the following tools to AI assistants:

| Tool | Description |
|------|-------------|
| `list_passports` | List and filter passports |
| `create_passport` | Create a new passport |
| `run_inference` | Execute AI inference |
| `chat_completion` | Run chat completions |
| `verify_receipt` | Verify a cryptographic receipt |
| `get_epoch` | Get epoch details |
| `check_health` | Check API health status |

## Links

- [MCP Server Source](https://github.com/raijinlabs/lucid-ai-sdk/tree/main/mcp)
- [Model Context Protocol](https://modelcontextprotocol.io/)
''')

print("\n✅ All SDK pages rebuilt from Speakeasy sources!")
print(f"Total namespace methods fetched: {sum(len(v) for v in namespaces.values())}")